### ISSUE TITLE
[BUG] Quick Crimes no remove button

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#123]
**Describe the bug**
There doesn't appear to be a remove button for quick crimes, but it does work.

**Screenshots**
![Screenshot_20200815-142425](https://user-images.githubusercontent.com/7302579/90312268-4e504200-df03-11ea-9e03-a727e69166e9.jpg)

**Smartphone (please complete the following information):**
 - Yandex

**Comment by Mephiles** [comment]
Fixed for 5.0 by switching 'Add' button with 'Edit' button to allow removing existing quick crimes.
