### ISSUE TITLE
[BUG] Travel visual glitch

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#128]
**Describe the bug**
Travel visual glitch

**To Reproduce**
unknown

**Screenshots**
[Screenshot](https://prnt.sc/u01g6e)

**Comment by DeKleineKobini** [comment]
I suspect it might have something to do with userdata not being loaded yet or something.

**Comment by Mephiles** [comment]
I think this has been resolved, closing for now. Open back up if still exists.
