### ISSUE TITLE
Stocks - notify when profix on stock group = x% or x Value

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#132]
**Is your feature request related to a problem? Please describe.**
Stocks - notify when profix on stock group = x% or x Value

**Comment by DeKleineKobini** [comment]
@Mephiles I don't think this is something we should add.

They can use the 'reaches price' for that imo.

**Comment by Mephiles** [comment]
We could allow percentages in the checkbox tho. For example you buy at $400 and u can set alerts for "reaches $420" or "reaches 105%" which could be converted and used as whole values in storage.

**Comment by DeKleineKobini** [comment]
Sure, will add the feature to allow for a % notification for v6.
