### ISSUE TITLE
Hide certain 'use' actions

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#152]
**Describe the solution you'd like**
Add options to hide actions like 'use another' and/or 'use another from faction'.

Not priority. For future consideration.

**Comment by DeKleineKobini** [comment]
I honestly don't see any reason for this.

**Comment by DeKleineKobini** [comment]
Feels like either the settings would be too complex, or it would be useless as I doubt it should be on for every item for anyone.
