### ISSUE TITLE
[BUG] Travel abroad doesn't include your benifits [PI/WLT] in profit/minute calcs

### ISSUE THREAD

**Issue by oojava** [Mephiles/torntools_extension#172]
**Describe the bug**
When viewing the travel table at home the profit/minute calc takes into account your flight type with the function "modifyTimeAndCost" This doesn't seem to exist when traveling abroad.

**To Reproduce**
1. Check profit/minute of an item before flying while holding a PI or WLT bb
2. Travel using PI or WLT bb
3. Compare the two values 

**Expected behavior**
The table while traveling abroad should be able to take into account your flight method and present you with accurate profit/minute calculations. 

**Screenshots**
On the travel screen at home (selected WLT bb)
![image](https://user-images.githubusercontent.com/2854960/92438490-89463e00-f16e-11ea-99e4-0c0447ed0dee.png)

On the travel screen while flying (flying with WLT bb):
![image](https://user-images.githubusercontent.com/2854960/92437157-e8568380-f16b-11ea-9b24-abd2d5df2498.png)

**Desktop (please complete the following information):**
(kinda irrelevant to this issue but...)
 - OS: archlinux
 - Browser firefox
 - Version 79.0

**Additional context**
It looks like the method searches the page to see if you have the flight method selected. Could this be changed instead to radio buttons while you're flying? 
```
        let airstrip = doc.find("#tab-menu4 li[aria-selected=true]").innerText === "AIRSTRIP";
	let wlt = doc.find("#tab-menu4 li[aria-selected=true]").innerText === "PRIVATE";
	let business = doc.find("#tab-menu4 li[aria-selected=true]").innerText === "BUSINESS";
```

**Comment by DeKleineKobini** [comment]
I've yet to test it, but it's very likely fixed now.

**Comment by Mephiles** [comment]
Seems like it's fixed, closing.
