### ISSUE TITLE
List of Stakeouts

### ISSUE THREAD

**Issue by jensdoecke** [Mephiles/torntools_extension#188]
This feature request ist possibly duplicate to  #135 (I'm not sure what is meant with WatchList)

I have some old stakeouts that I don't want anymore. But I don't know on which player I activated Stakeout.
The current solution is to wait for the notification and go on the profile to deactivate or change the Stakeout.

I would like to have a list with all active stakeouts, where I can change the settings like on the profile page.

**Comment by DeKleineKobini** [comment]
It's been added to the popup.
