### ISSUE TITLE
[BUG] Notifications Disabling Not Working

### ISSUE THREAD

**Issue by dssecret** [Mephiles/torntools_extension#190]
**Describe the bug**
After I disabled notifications, I still get the notifications

**To Reproduce**
1. Disable notifications
2. Do something to get notifications

**Expected behavior**
I expected to not get any notifications

**Screenshots**
![Settings](https://user-images.githubusercontent.com/37424786/93139844-52a08400-f696-11ea-8ee1-fc948c554553.png)

![Notifications](https://user-images.githubusercontent.com/37424786/93139864-57fdce80-f696-11ea-965c-40321dda5bad.png)

**Desktop**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Firefox
 - Version: 80.0.1

**Comment by DeKleineKobini** [comment]
Are you sure that you actually saved the settings? Can't see any reason why it wouldn't work.

**Comment by dssecret** [comment]
Recently it stopped giving me notifications, but I haven't changed anything between now and then.

**Comment by DeKleineKobini** [comment]
![Screenshot](https://i.imgur.com/OogY004.png)

**Comment by dssecret** [comment]
What is this?
Sorry for the late reply.

**Comment by DeKleineKobini** [comment]
It's a screenshot of my life notifications being off, and me receiving a life notification.

**Comment by Mephiles** [comment]
I think the latest Notifications fix with v5.2 (if I remember correctly) has fixed the issue. Reopen if appears again.
