### ISSUE TITLE
Showing your Vault share with an asterisk

### ISSUE THREAD

**Issue by Johanmans10** [Mephiles/torntools_extension#191]
I recently discovered that you can choose to only show your part of your property vault under your cash balance. I never needed it before, but my spouse recently also started using our vault. I really don't mind, but knowing how much money I have in there is way more useful then knowing how much is in the vault in total.
This feature is perfect apart from one thing. The asterisk.
I get that it's there to show that it's only showing your part and not the total, but is there any way you would be able to make it removable? Or could you perhaps move it to be "Vault*:  $xxx" instead of "Vault:  *$xxx"? I just get a bit annoyed when I see that the $ sign of the vault doesn't line up with the $ sign of my balance.

**Comment by DeKleineKobini** [comment]
Might be added in v6, I don't remember. If still an issue and still wanted, report it again after the release.
