### ISSUE TITLE
[BUG] No notifications sounds.

### ISSUE THREAD

**Issue by WiffleB** [Mephiles/torntools_extension#192]
**Describe the bug**
Notifications have stopped making sounds

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - Version v5.0.1

**Comment by DeKleineKobini** [comment]
Can replicate on Vivaldi on Windows Education (basically Windows Pro, but for free in a legal way xD).

**Comment by WiffleB** [comment]
I don't know what it was. I uninstalled torn tools and chrome and started
over. Sounds are working again.

**Comment by DeKleineKobini** [comment]
Yeah, they are working for me too now.

**Comment by DeKleineKobini** [comment]
I've got a report that this is still an issue.

**Comment by DeKleineKobini** [comment]
With a better system, I'll assume it's fixed, otherwise we'll reopen this.
