### ISSUE TITLE
Show weapon experience and hits required.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#196]
**Additional context**
Request permisission from Untouchable [1360035]

**Comment by DeKleineKobini** [comment]
Can't find the formula (original script is copyrighted, so I don't want to use that).

**Comment by Mephiles** [comment]
@Sashank999 might be something you would want to do?

**Comment by DeKleineKobini** [comment]
I don't want to add any more feature that weren't actually suggested, so closing this one. Neither do we seem to have the required information etc.
