### ISSUE TITLE
Forum enhancements.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#199]
**Describe the solution you'd like**
- [ ] Copy post formatted for Discord.
- [ ] Hide a user's threads.
- [ ] Hide a user's posts.

**Additional context**
Original by DoctorN.

**Comment by Mephiles** [comment]
Seems like this has been added, closing.

**Comment by Mephiles** [comment]
Reopened, wants finishing touches

**Comment by Sashank999** [comment]
I think it is now fully functional and perfect. Better close this.
