### ISSUE TITLE
Bug: Gym Merit Tracking 

### ISSUE THREAD

**Issue by jgonyea** [Mephiles/torntools_extension#2]
The display of the TT Awards section at the gym appears broken.

Example:
Strength: 226,329.6,725/1,000,000

I'm not sure what that ",725" is doing there.

**Comment by Mephiles** [comment]
I see where the problem comes. I have a function for turning numbers like "1000000" into "1,000,000" and there are 4 numbers after the decimal point. 

I will fix it in the next update.
