### ISSUE TITLE
[BUG] Purchasing w/ mission credits

### ISSUE THREAD

**Issue by kennymac782641** [Mephiles/torntools_extension#204]
**Describe the bug**
After purchasing items, under missions, with mission credits. Ammo owned value is not immediately shown again, the page must be reloaded.
https://gyazo.com/984c8907ea8d1fb7b0b5f2324efe6e7c

Second, after purchasing something under missions all values vanish.
Opera GX  https://gyazo.com/7556436868c6550ccdb68b073a4752f0
Edge(Chromium)  https://i.imgur.com/LFuGMmh.png

**Expected behavior**
1. Values are reloaded with having to reload the page.
2. Values do not disappear upon purchase.

Version 5.0.1

Originally reported on Opera GX
Confirmed same behavior on Edge(Chromium)

**Comment by DeKleineKobini** [comment]
These issues are solved already for the next update.
