### ISSUE TITLE
[BUG] Drug tips not working properly.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#205]
**Screenshots**
![Demo](https://user-images.githubusercontent.com/8469800/100550073-97e35380-328c-11eb-8dfe-3b4aa52d440d.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by DeKleineKobini** [comment]
I can't replicate it myself.

**Comment by jgolla** [comment]
I saw this by:
1. clicking on Xanax (tips work fine)
1. click Xanax again (tips go away)
1. click Xanax again (they appear then disappear like the gif)
