### ISSUE TITLE
[BUG] OC shows NNB regardless of DoctorN being loaded or not

### ISSUE THREAD

**Issue by dang-nabbit** [Mephiles/torntools_extension#208]
started happening a couple days ago without any update that i know of. still happens when i deactive scripts and doctorn, but stops happening when i deactivate TT.

![unknown 1](https://user-images.githubusercontent.com/34625456/93793133-cac5f700-fc0c-11ea-944a-47d43d95254d.png)

**Comment by DeKleineKobini** [comment]
Now that I look closely at it, 1 column is probably DoctorN instead of TornTools. The reason is because TT doesn't show a * for non-updated nnb values, while DrN does.

**Comment by DeKleineKobini** [comment]
It was confirmed as DoctorN. This changes the issue to the DrN comparability not working correctly.
