### ISSUE TITLE
[BUG] Can't export settings.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#209]
**Screenshots**
![Screenshot](https://i.imgur.com/rFB1oxn.png)

**Desktop (please complete the following information):**
 - Version 5.1 BETA

**Comment by raxty** [comment]
@DeKleineKobini This has been fixed with 2934023f09dbf46a7832161e62eb325207dbc55c, right?

**Comment by DeKleineKobini** [comment]
It indeed was.
