### ISSUE TITLE
[BUG] Quick crimes dont work after captcha unless I refresh

### ISSUE THREAD

**Issue by dang-nabbit** [Mephiles/torntools_extension#213]
**Describe the bug**
if i do a captcha on the crime page, the quick crimes buttons dont work and the crime list loads with a strange design (looks like without any CSS borders)

nothing pops up in console

refreshing the screen fixes

**To Reproduce**
1. Go to crimes page when a captcha is due
2. Do the captcha
3. Crime list loads without borders
4. Click on a quick crime button
5. Doesn't work
6. Refresh to fix

**Expected behavior**
Completing a captcha on crime page should make everything work as usual

**Screenshots**
weird looking crime list:
![unknown 3](https://user-images.githubusercontent.com/34625456/94074880-7f5c4600-fdd0-11ea-8012-d6deab74972d.png)
console without anything related
![unknown 1](https://user-images.githubusercontent.com/34625456/94075847-4ae98980-fdd2-11ea-9e97-ae3138972935.png)

**Desktop**
 - Win10
 - Chrome 85.0.4183.102
- TT v5.0.1

**Comment by dang-nabbit** [comment]
Seems like this only happens if i have "reCaptcha" set as default. will test more to isolate the issue and  post more info here

**Comment by dang-nabbit** [comment]
It happens when u do recaptcha, regardless of it being set as default

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6. Report again if it's an issue after its release.
