### ISSUE TITLE
[Suggestion] Add an option to hide the show/hide chat button

### ISSUE THREAD

**Issue by smikula** [Mephiles/torntools_extension#225]
**Is your feature request related to a problem? Please describe.**
The show/hide chat button interferes with (overlaps) UI from another plugin I use.

**Describe the solution you'd like**
It would be great to have an option to remove it.

As a related suggestion, it might be worth having a "Chat" tab in the preferences UI.  Right now there are several options related to chat scattered throughout the other tabs.

**Comment by DeKleineKobini** [comment]
It was added, so I will be closing this.
