### ISSUE TITLE
Can't drag anything to quick crimes on Chrome/Linux [BUG]

### ISSUE THREAD

**Issue by RHendery** [Mephiles/torntools_extension#229]
**Describe the bug**
On Chrome, on the crimes page, the quick crimes box is visible, but dragging crimes to it does nothing. 

**To Reproduce**
Go to crimes, click on a type of crimes (e.g. "arson"), try to drag the specific crime (eg. "warehouse" into the torntools quick crimes box at the top of the screen). 

**Expected behavior**
I expect this to populate quick crimes with a clickable crime shortcut, as it does in Firefox and Kiwi browser. (And I think did in Chrome until a few days ago), and as it does in the quick items (which is still working fine).

**Desktop (please complete the following information):**
 - Ubuntu
- Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6. Report again if it's an issue after its release.
