### ISSUE TITLE
Auto max buy while abroad.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#242]
**Describe the solution you'd like**
Auto max buy while abroad.

**Additional context**
Requiring permission from Torn. Or @Mephiles permission to just go ahead, as it technically isn't forbidden by the rules.

**Comment by hvr-lust** [comment]
Do we have permissions for this? seems quite easy to do

**Comment by Mephiles** [comment]
Yes go for it
