### ISSUE TITLE
Show flight times before flying.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#245]
**Describe the solution you'd like**
Show flight times before flying.

**Additional context**
[!Screenshot](https://cdn.discordapp.com/attachments/726581776239165551/763862052996907108/unknown.png)

**Comment by juzraai** [comment]
I suggested this thing on Discord, the screenshot shows the first version of my userscript. Now I've redesigned (and rewrote) it completely to look nicer. You can find it here: https://github.com/juzraai/torn-flight-times :)

![](https://github.com/juzraai/torn-flight-times/raw/main/screenshot.png)
