### ISSUE TITLE
Value of your own Bazaar

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#246]
**Describe the solution you'd like**
Show the value of your own Bazaar both when Open/Closed.

**Comment by DeKleineKobini** [comment]
While closed might not be possible.

The user/bazaar call only shows a value for open bazaars, including your own bazaar. So we'd have to scrape the page, but not all items might be loaded.

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6.
