### ISSUE TITLE
Notes Improvement

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#249]
**Describe the solution you'd like**
This feature is handy (even if you have donator status), however its a little annoying having to scroll down to it if you have a few too many Custom Links like I do. Would be nice if there was an option to push it up to the top right of the browser window where there is nothing it could block anyway, especially if you use the Align To Left feature.

**Comment by DeKleineKobini** [comment]
I honestly don't have any intention to make show it another place, what are your thoughts? @Mephiles

**Comment by Mephiles** [comment]
I think the new custom links implementation will remove the clutter a bit allowing users to place less-used custom links under the Areas container.

**Comment by DeKleineKobini** [comment]
Okay, I'll close this then.
If they want it anyway, reopening or making a new issue isn't a problem.
