### ISSUE TITLE
Sidebar bars

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#251]
*Describe the solution you'd like**
As you have the OC countdown available underneath the bars, it would be nice if there was an option to add Bank Investment countdown there as well.

With Nerve and Energy countdowns its sometimes a little annoying trying to calculate what time the bar will be full, it would be nice to have an option that could change the Energy & Nerve tick countdown to a total countdown.

**Comment by DeKleineKobini** [comment]
As your bank investment and the energy/nerve ticks all allow you to hover over them to see their total countdown, I don't really think this is something we'd add. Thoughts @Mephiles?

**Comment by Mephiles** [comment]
Yea I agree, as you can see them already by hovering, it would just clutter the sidebar with duplicate info.

**Comment by DeKleineKobini** [comment]
Okay, then I'll be closing this.
