### ISSUE TITLE
Inline gym requirements.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#254]
**Describe the solution you'd like**
Show gym requirements in line

![Screenahot](https://i.imgur.com/ULgYm5R.png)

**Comment by XDelta** [comment]
As reference, those inline requirement amounts from the screenshot are from [this userscript](https://greasyfork.org/en/scripts/14778-special-gym-ratios). I would like to see this incorporated as well. It additionally has an option for no specialty

**Comment by DeKleineKobini** [comment]
This will be added for v6.

![Default](https://i.imgur.com/cvRatyQ.png)
![Screenshot](https://i.imgur.com/zjrNF6b.png)
