### ISSUE TITLE
Stock total worth and profit/loss.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#260]
**Describe the solution you'd like**
Stock total worth and profit/loss.

**Comment by Sashank999** [comment]
I think this is already there.
![Stock Exchange _ TORN - Google Chrome 10-Jan-21 11_25_03 AM](https://user-images.githubusercontent.com/76554862/104115600-e594b680-5336-11eb-94ba-c364c82db561.png)

**Comment by DeKleineKobini** [comment]
The current think is individual, not total of your portfolio.

**Comment by Mephiles** [comment]
Total worth was added, how should profit/loss be added for total? There should be some anchor point but I think the Networth statistics on the Home page is enough, no need to double the info.

Thoughts?

**Comment by DeKleineKobini** [comment]
The networth is daily difference, not from ehen you had the stocks.
