### ISSUE TITLE
[BUG] Dragging crime from main crime list redirects page to null

### ISSUE THREAD

**Issue by XDelta** [Mephiles/torntools_extension#261]
**Describe the bug**
Dragging a crime from the main crime list (category list) to the quick crimes bar will redirect the page to null and then some browsers will interpret that to null.com.

**To Reproduce**
1. Go to https://www.torn.com/crimes.php
2. Click and drag any crime image to the top where quick crimes are
3. Quick crimes appears to accept the drag and drop by changing the mouse cursor
4. Page gets redirected to null upon dropping image

**Expected behavior**
Drag and drop shouldn't work on the main crime steps, at least silently ignore instead of redirect the page to null (and in some cases to null.com)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Firefox
 - Version: 81.0.2

**Additional context**
Disallow dropping on the main crime step, and/or ignore the invalid crime and not redirect

**Comment by XDelta** [comment]
Looks like it can just redirect to the crime image url as well

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6. Report again if it's an issue after its release.
