### ISSUE TITLE
Custom links sorted into Areas sidebar

### ISSUE THREAD

**Issue by XDelta** [Mephiles/torntools_extension#262]
**Describe the solution you'd like**
I would like to put custom links in the side bar that are sorted after specified areas. As example under Items I have a link to Bits N Bobs, My Bazaar, and the Item Market

**Describe alternatives you've considered**
I've made this as a userscript myself by directly inserting divs after items.
![925b543a](https://user-images.githubusercontent.com/7883807/95945313-05035e00-0d9f-11eb-87e0-26f57ebc03ce.png)

**Comment by Mephiles** [comment]
How do you see the configuration page done so it's effective and user-friendly?

**Comment by Zwizzor** [comment]
I would like an option to display the custom links menu below the regular links menu. Without necessarily going into something as advanced as inserting links anywhere, I believe the default link are more important than my custom ones, so I would like to do less scrolling and keep the custom links lower.

Additionally while we're on the topic, a way to reorganize custom links entries within themselves would be great, with a drag and drop or arrow system.
