### ISSUE TITLE
Rearrangement of Custom Links

### ISSUE THREAD

**Issue by ghost** [Mephiles/torntools_extension#272]
**Describe the solution you'd like**
Add the ability to rearrange custom links.

**Comment by Zwizzor** [comment]
I agree. Both a way to rearrange custom links within the custom links list would be very convenient instead of having delete and re-add links to sort them the way we want. Additionally I would also very much like the ability to display the custom links below the default links, instead of above.

**Comment by DeKleineKobini** [comment]
This has been added for v6.
