### ISSUE TITLE
[BUG] Missing mission info: Three-peat

### ISSUE THREAD

**Issue by smikula** [Mephiles/torntools_extension#273]
**Describe the bug**
This mission has no information or help text from TT.  (I get "Hint: Contact the TornTools developers")

**Mission text**
Three-peat | Medium

You ever see those horsey contests? I think they call them requestrian or something. Anyway I watched it on TV yesterday and the way they pick the winner is by making the horse do a bunch of things, pacific things, like a funny dance or a jump over a log or stuff.

Apparently it's hard to make the horse do pacific things you want, so it's cleverer when they do it. I want you to be cleverer, so you're gonna do three pacific tasks to focus your brain. You can do them in any order, hit on anyone you want, but you have to do all three. I want everyone to see my horse is the best and can take pacific instructions like this.

**Mission tasks**
* Defeat any target and leave them
* Defeat any target and mug them
* Defeat any target and hospitalize them

**Comment by Mephiles** [comment]
@smikula can I close this?

**Comment by smikula** [comment]
Yes, it's fixed.
