### ISSUE TITLE
[BUG] Error in definition of mission "Tree Huggers"

### ISSUE THREAD

**Issue by kontamusse** [Mephiles/torntools_extension#277]
The task description of the mission "Tree Huggers" says "Defeat 6-8 (P)".
This mission asked me to defeat 6 players.
Therefore it should be changed to "Defeat 5-8 (P)"

My Torn nick is kontamusse

**Comment by kontamusse** [comment]
I posted the fix as a fork from torntools/scripts/content/missions/ttMissions.js

**Comment by Mephiles** [comment]
@kontamusse can i close this?
