### ISSUE TITLE
[BUG] Defends counted as Win

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#281]
**Describe the bug**
Defends are counted as Win for battle stats.

**Comment by h4xnoodle** [comment]
which also means `Defends Won` is 0 when viewing the list on Missions screen.

**Comment by DeKleineKobini** [comment]
> which also means `Defends Won` is 0 when viewing the list on Missions screen.

I don't think those are related though.
Those stats for achievements come from the `user/personalstats` api, while the attack history uses `user/attacks(full)` and we store the results ourselves.

**Comment by DeKleineKobini** [comment]
Solved in v6.
