### ISSUE TITLE
[Feature Request] Events page filtering

### ISSUE THREAD

**Issue by N-kay** [Mephiles/torntools_extension#284]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to filter event types. Similar to faction member filtering.

**Describe the solution you'd like**
A TornTools box on the events page, similar to the one for the faction member page.
Possible filters: Attacks (subtypes attacks, mugs, hosped), Market (subtypes trades, stocks, point market, bazaar), Stock benefits, OCs, Company trains, Items received

**Describe alternatives you've considered**
Maybe like a events tab on the TT popup? Could be implemented from scratch instead of filtering the existing page.

**Additional context**
This is just a nice to have thing, no desperate need.

**Comment by DeKleineKobini** [comment]
I'll look into it for v6.
I should note that it wouldn't decrease the pages you'd have to look though, but would only filter them on the currently viewed page.

**Comment by DeKleineKobini** [comment]
I don't see much reason to include this anymore. Just use the activity log and the included filter.
