### ISSUE TITLE
Make Market and Stocks tab force focus on search input

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#290]
i think it's a better user experience if market and socks tab force focus on search inputs when visiting these tabs

**Comment by DeKleineKobini** [comment]
I can agree with it on the market tab, as the search is the only feature there.
Not sure for the stocks tab though.

**Comment by dev-masih** [comment]
just market tab is more enough for me, thanks

**Comment by dev-masih** [comment]
so now that you guys considering this, I'll propose one step further, when you search in the input field made it so you can jump on the result list with arrow up and down keys and with pressing enter see the item price in the market, completely mouse free eperience.

**Comment by DeKleineKobini** [comment]
I do think that's a great idea, but I wouldn't really know on how to do it, so it will not be included in v6.0.0. You can make another issue for it though, so it could be added in another version. I just don't want to delay v6.0.0 even more by spending a whole weeks worth of time (which isn't that much, as I can only work in the weekends pretty much) for something like this.
