### ISSUE TITLE
Suggestion to create a more compact category list layout for item market

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#291]
when visiting item market if you want to checkout lower categories like plushies, special items or misc category each time you have to scroll down and scroll back up to see the top items, i suggests a more compact replacement layout that allows user to select each category without need to scroll, like for example you can remove the category names and place each two category icon in a row, or any other solution 
thanks

**Comment by DeKleineKobini** [comment]
Will look into the possibilities for v6.

**Comment by DeKleineKobini** [comment]
![image](https://user-images.githubusercontent.com/7302579/128003113-c7d1e99c-1bd7-456b-af53-131917dd73cf.png)

How does this look?

**Comment by Mephiles** [comment]
> ![image](https://user-images.githubusercontent.com/7302579/128003113-c7d1e99c-1bd7-456b-af53-131917dd73cf.png)
> 
> How does this look?

Could the icons not be shrunk? This could be one of the options to shrink the whole list but I also do like the suggestion of just icons in a grid for extra-compact. If that is doable.

**Comment by DeKleineKobini** [comment]
> Could the icons not be shrunk? This could be one of the options to shrink the whole list but I also do like the suggestion of just icons in a grid for extra-compact. If that is doable.

I tried to shrink the icons, but due to how they are displayed (`background-image`), it's not really possible to shrink it.
I'm personally not a fan of a icon-only grid layout, as you've have to think about what icon is what. And due to the above issue, they would have to be the same size as the normal layout.

**Comment by DeKleineKobini** [comment]
Will not be included and closed due to a lack of input by the poster.

**Comment by dev-masih** [comment]
hey, sorry didn't think i should get involved more, if shrinking the icons are not an option the way that the image looks is perfect as well
