### ISSUE TITLE
Make Market tab experience mouse free

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#292]
i think it's a better user experience when you search in the input field made it so you can jump on the result list with arrow up and down keys and with pressing enter see the item price in the market, completely mouse free eperience.

i'm reposting this suggestion to be considered after v6.0.0

**Comment by DeKleineKobini** [comment]
Might look into it for v6, no promised though.

**Comment by DeKleineKobini** [comment]
I've looked at it, but doesn't really seem worth our effort as I doubt more than a handful of TT users would use it.
