### ISSUE TITLE
Adding bazaar item highlight for opening a bazaar url in a new tab

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#294]
in item market when you select a bazaar the URL gets additional parameters like 'tt_itemid' and 'tt_itemprice'.
i propose to modify the actual URL to add these parameters to support the highlight even when opening the bazaar in a new tab

**Comment by DeKleineKobini** [comment]
It's more like a bug that it doesn't already do that.

Will look into it or v6.

**Comment by Sashank999** [comment]
Can you reconfirm this @dev-masih ? I really think it is working normally and there is no bug here. It is functioning as intended and also works for new tabs.

Also, if you can confirm that this bug exists, please also send the Item Name and Bazaar URL opened.

**Comment by dev-masih** [comment]
tested on version 5.5 this still happening

![bazaar_highlight](https://user-images.githubusercontent.com/8469800/105857004-16474200-5fff-11eb-905c-d43b83ba9f0e.gif)

as you can see when you open bazaar page in new tab highlight parameters is not there but when you just open it normally they are there
I'm using latest version of chrome
