### ISSUE TITLE
Health Watch

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#295]
**Describe the solution you'd like**
Watch the health on the page and send a notification if it drops.

**Additional context**
Not using the API, due to the delay, this will require a `document.hasFocus()` check, to be within the rules. It won't work while not on Torn either.
- [ ] Require permission from bogie or IBF.

**Comment by DeKleineKobini** [comment]
Possible, legal, but in my opinion not something we should do. Thoughts @Mephiles?

**Comment by Mephiles** [comment]
Yea, I don't really like it either.

**Comment by DeKleineKobini** [comment]
Then it's an easy one.
