### ISSUE TITLE
[BUG] torntools updated green bar keep showing each time browser opens

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#296]
each time i opens the browser and go to torn the green bar that says torntools updated in areas section appears and i have to click it and see the changelog to get rid of it but if i close the browser and open it again it appears again, please fix this, thanks.
i'm using the latest version of chrome

**Comment by DeKleineKobini** [comment]
This is not a bug.

It has been changed for 6.0 though.
