### ISSUE TITLE
[BUG] "Safari" mission hint

### ISSUE THREAD

**Issue by factoryman942** [Mephiles/torntools_extension#299]
Safari mission hint says "use ONLY the rifle", but the mission is completable with non-damaging temps:
https://www.torn.com/loader.php?sid=attackLog&ID=a78784d5310553d0d8f4b3b7db746008
![image](https://user-images.githubusercontent.com/20996272/102154656-c73fb600-3e71-11eb-84e3-7a8af8b39131.png)

**Comment by DeKleineKobini** [comment]
With the rewrite (v6), I've rewritten them all. Hints like this, that feel a bit stupid, have been removed entirely.
