### ISSUE TITLE
[BUG] Missing mission info

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#302]
**Describe the bug**

Mission: Undercutters (Diff: Easy)

fadarve and his two cronies are trying to put me out of business! Those sneaky rat-faced...oooh man are they gonna get it. They thought it was a good idea to set up another loan business and undercut what I charge. I barely scrape by, you know. And when you get a loan from me you know it's good quality. I even got my cash laundered at the laundromat cause I heard it's smart to do that. Some of it got messed up but most of it smells great now. See, that's the trouble I go to for my clients, would these jerks do that? No. There's no room in this town for rinky-dink lenders. Just me. Run those clowns out of town for me kid.
TornTools mission Information
Task: Couldn't find information for this mission.
Hint: Contact the TornTools developers.
- Defeat fadarve
- Defeat freitas-j-2k7
- Defeat foofamaster

**Comment by DeKleineKobini** [comment]
Did you have this yourself or someone else? The mission information is entirely correct, so I suspect them using another mission script.

**Comment by Mephiles** [comment]
Was a user report, I'll close this as the info is in our files.
