### ISSUE TITLE
Portfolio total value

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#304]
**Describe the solution you'd like**
Show total portfolio value (could be displayed nicely in the 'Your portfolio' heading). Apparently was available on Doc.

**Comment by DeKleineKobini** [comment]
Great idea, but it wasn't available on DrN either.

**Comment by Sashank999** [comment]
But that doesn't mean we shouldn't add it to TT. I have the code but got no idea where to add :
`let totalPortfolio = document.createElement("div");
totalPortfolio.id = "tt-totalPortfolio";
totalPortfolio.className = "m-top10 tt-title title-green all-rounded";
let sum = 0;
// Loops through all the li elements (stock blocks)
for (let element of document.findAll('.stock-main-wrap>ul.stock-cont>li.item-wrap')) {
	sum += parseInt(element.find('.item .info .c-price-wrap .first-row span').innerText.replace('Worth: ', '').replace('$', '').replace(/,/g, '').trim());
}
sum = new Intl.NumberFormat('en-US', {
	style: 'currency',
	currency: 'USD',}).format(sum).slice(0, -3);
document.querySelector("#info_wrapper").insertAdjacentElement("beforeBegin", totalPortfolio);
totalPortfolio.innerHTML = `Total Portfolio Value : ${sum}`;
totalPortfolio.insertAdjacentHTML("afterEnd", "<br>");
`

**Comment by Mephiles** [comment]
DKK didn't say we shouldn't add it, he just brought out the fact that it wasn't available in Doc :P. We can surely add it in. As I said, you should create a new branch called "portfolio-total-value" or something, write the code, create a Pull Request to merge it into master so me or DKK can approve it.

**Comment by DeKleineKobini** [comment]
Indeed, my answer indeed just stating that the information about it being in DrN was wrong.

About the code snippet, what I'm afraid of with just using that code is mobile, I'm almost certain that it will give errors.

**Comment by DeKleineKobini** [comment]
Might also be worth adding #260 into this. 

If not, I will add it to v6 anyway.

**Comment by Sashank999** [comment]
I don't understand what @DeKleineKobini said.

> Indeed, my answer indeed just stating that the information about it being in DrN was wrong.
> 
> About the code snippet, what I'm afraid of with just using that code is mobile, I'm almost certain that it will give errors.

**Comment by Sashank999** [comment]
#307

**Comment by Sashank999** [comment]
Added by pull request #307 .

**Comment by DeKleineKobini** [comment]
> I don't understand what @DeKleineKobini said.
> 
> > Indeed, my answer indeed just stating that the information about it being in DrN was wrong.
> > About the code snippet, what I'm afraid of with just using that code is mobile, I'm almost certain that it will give errors.
> 
> Are you saying that the code gives errors on mobile ?

What I meant is that it might. It doesn't, but you clearly didn't test your PR (check the review I did).
