### ISSUE TITLE
[BUG] High-low helper sometimes displays no suggestion or the previous one

### ISSUE THREAD

**Issue by pdxchoice** [Mephiles/torntools_extension#305]
**Describe the bug**
Often when playing high-low it stops working and doesn't display any suggestion, or displays the previous suggestion as well as the current one, etc.

**To Reproduce**
1. Go to play high-low in the casino
2. Click through kinda fast(?)

**Expected behavior**
The game should always display a single suggestion.

**Screenshots**
![image](https://user-images.githubusercontent.com/10791719/103159150-cbce6d80-4793-11eb-8328-d82162662b7b.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 87

**Comment by Mephiles** [comment]
It is most likely, as you said, because of "Click through kinda fast(?)". The current form of the script doesn't have much modularity and depends on some good timings. The script might just "get lost" when clicking through fast.

Will try to improve on the re-write (v6).

**Comment by Sashank999** [comment]
Fixed with PR #435 .

**Comment by Sashank999** [comment]
Fixed. Now please close this.
