### ISSUE TITLE
B&I Warning

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#306]
**Is your feature request related to a problem? Please describe.**
Torn Staff is receiving a lot of bug reports due to TT issues.

**Describe the solution you'd like**
I personally see 2 (similar) options:
1. We show a decently sized warning that they should first disable TT before trying to replicate the issue again.
2. We disable posting bug reports in general when TT is enabled.

**Additional context**
Solution 1 might not decrease the reports by a lot.
Solution 2 on the other hand might add more problems, as they would likely report directly using chat or messages instead knowing them.

**Comment by DeKleineKobini** [comment]
These are some solutions I've thought of for Torn to receive less TT-based reports. What are your thoughts on those, @Mephiles?

**Comment by Mephiles** [comment]
I think adding a big red banned on the B&I page will at least reduce the false posts 70-80%. So option 1 would be good enough.
