### ISSUE TITLE
[BUG] My own faction filter on Jail page does not work. 

### ISSUE THREAD

**Issue by TheCodeSinger** [Mephiles/torntools_extension#313]
**Description**
When on the Jail page, the Torn Tools UI defaults to my faction "Equilibrium" in the Faction filter, but this filter value does not work. It does not show my faction members when they are in jail. The other factions in the list work properly. 

I believe the issue is because the value of the option for my faction is the full name equilibrium instead of its tag, as is the case with all of the other factions in the generated list based on who is in jail at the time. See the inspector panel in the attached screenshot.

**To Reproduce**
Go to Jail page when someone from your faction is in Jail. Note that the list is empty even though your own faction is preselected in the Faction filter.

**Expected behavior**
I expect to see my faction members listed.

**Screenshots**
![Screen Shot 2021-01-06 at 11 58 02 AM](https://user-images.githubusercontent.com/1916180/103814400-73f6f880-5016-11eb-8039-b5d3dd7b3430.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Both Firefox 84.0.1 and Chrome 87.0.4280.88

**Comment by TheCodeSinger** [comment]
Additionally, I would prefer to default to None rather than my own faction. Or have a setting to specify the default, one over the other.

**Comment by DeKleineKobini** [comment]
You have to enter your short name, so it would be EQ for your faction.

> Additionally, I would prefer to default to None rather than my own faction. Or have a setting to specify the default, one over the other.
This is already possible, with the radio button in the settings in front of the faction names.

**Comment by TheCodeSinger** [comment]
Perhaps next in the Torn Tools settings you should add next to the faction filter that it should be the faction tag not the name. Thanks!

**Comment by DeKleineKobini** [comment]
[My suggestion](https://www.torn.com/forums.php#!p=threads&f=19&t=16205000) might make it possible for us to add a placeholder for your own faction. We'd have to wait at least till Tuesday to know what exactly he changed though.
