### ISSUE TITLE
[BUG] there is not max button for items in bazzar

### ISSUE THREAD

**Issue by dev-masih** [Mephiles/torntools_extension#322]
after updating the extension to version 5.4 i can't see any max on bazaar items that i can select to fill the number of items buying to max available.

**Comment by DeKleineKobini** [comment]
Sorry to disappoint, but it's not an issue after updating to v5.4. It's been an issue since around noon, with the Torn Tuesday update.

It's part of a lot of issues which will take a few days.

**Comment by Sashank999** [comment]
This is fixed. Better close this.

**Comment by dev-masih** [comment]
yes it fixed, thanks

**Comment by dev-masih** [comment]
im reopening this issue as the problem on desktop is resolved but in mobile there is still no "max" button for items

![Uploading Screenshot_20210126-175454_Kiwi Browser.jpg…]()


I'm using tt5.5 on kiwi browser
