### ISSUE TITLE
Incorrectly Showing Custom Links Section

### ISSUE THREAD

**Issue by NotKoalafied** [Mephiles/torntools_extension#359]
**Describe the bug**
The Custom Links section on the sidebar no longer displays above the Areas section. Now it displays at the bottom.

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Ensure that there is at least one custom link defined in TT settings.
2. Open/reload Torn

**Screenshots**
![image](https://user-images.githubusercontent.com/71797215/105914738-58b75180-5ff4-11eb-980d-4a958fa5e984.png)

If you feel like the following information is important then please fill in:
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by DeKleineKobini** [comment]
This was fixed in v5.6, which will release soon.
