### ISSUE TITLE
[BUG] Chain timer flickers when not needed.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#361]
**Describe the bug**
The chain timer flickers when in cooldown or before it's an actual chain (less than 10 hits).
I've also noticed that it sometimes stays red, might be because of multiple tabs though.

**Comment by DeKleineKobini** [comment]
@Sashank999 Maybe you can look into this?

**Comment by Sashank999** [comment]
I will.
