### ISSUE TITLE
[BUG] Notes is now located under the sidebar

### ISSUE THREAD

**Issue by Cringely** [Mephiles/torntools_extension#366]
**Describe the bug**
Notes text block is now located under the sidebar.

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Login to Torn with TornTools enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/759077/106307601-677c4f00-6214-11eb-98c7-52dbe2f1d40a.png)

If you feel like the following information is important then please fill in:
**Desktop (please complete the following information):**
 - Browser Brave & Chrome
 - Version Brave 1.19.88 Chrome 88

**Comment by Allo101** [comment]
this is already fixed for the upcoming 5.6.1 update

**Comment by DeKleineKobini** [comment]
As Allo said, this has been fixed for the next version.
