### ISSUE TITLE
[BUG] Hiding gym highlight without highlight = no background.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#375]
**Screenshots**
![Screenshot](https://i.imgur.com/MK55mIG.png)

**Comment by DeKleineKobini** [comment]
@Sashank999

**Comment by Sashank999** [comment]
I actually find the code working in my PC. Is this in mobile ?

**Comment by DeKleineKobini** [comment]
> I actually find the code working without any issue on my PC. Is this in mobile ?
I'm running Vivaldi (Chromium-based browser) on Windows, not any mobile (I don't use TT on mobile).

**Comment by DeKleineKobini** [comment]
Also an issue on Chrome for me.
