### ISSUE TITLE
[BUG] Awards not closing in thee sidebar when clicking the arrow for certain tabs

### ISSUE THREAD

**Issue by Pentillum** [Mephiles/torntools_extension#379]
**Describe the bug**
The awards side bar tab when ticked to close still shows the awards but it overlaps with the list of friends,  and server time.

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Click on 'either home, items, gym, crimes, or missions' on the side bar.
2. See error

**Screenshots**
If possible, add screenshots to help explain your problem.
![2021-02-05_15-53-16](https://user-images.githubusercontent.com/59666465/107005551-d0426900-67ca-11eb-9983-3d41732e752a.png)
![brave_2021-02-05_15-51-29](https://user-images.githubusercontent.com/59666465/107005555-d1739600-67ca-11eb-9a47-fd88055a0780.png)
![brave_2021-02-05_15-53-26](https://user-images.githubusercontent.com/59666465/107005557-d20c2c80-67ca-11eb-810f-d9be0ad29477.png)
![brave_2021-02-05_15-53-45](https://user-images.githubusercontent.com/59666465/107005558-d20c2c80-67ca-11eb-98da-59ab0cfaee2a.png)

If you feel like the following information is important then please fill in:
**Desktop (please complete the following information):**
 - Browser [Brave]
 - Torntools Version 5.6.1

**Comment by Sashank999** [comment]
Yes, that is a bug due to recent TORN update. It is fixed in the repo.
This better be closed as this is already fixed.

**Comment by DeKleineKobini** [comment]
> Yes, that is a bug due to recent TORN update. It is fixed in the repo version and will be available for update in the next release.
> This better be closed as this is already fixed.

Indeed, I overlooked that it was fixed for 5.7 instead of 5.6.1, so I kept it open.
