### ISSUE TITLE
[BUG] Address is suggested in chat

### ISSUE THREAD

**Issue by WizardRubic** [Mephiles/torntools_extension#382]
**Describe the bug**
Address is suggested on chat boxes on certain pages with torn tools on and address suggestions on with chrome

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Be on chrome
2. Turn on save and fill addresses at chrome://settings/addresses
3. Add an address
4. Go to https://www.torn.com/factions.php?step=your#/
4. Open Global chat and click the input text area of the chat box

**Screenshots**
![](https://i.imgur.com/EoEevor.png)

If you feel like the following information is important then please fill in:
**Browser:**
 - Chrome 88.0.4324.146

**Comment by DeKleineKobini** [comment]
This is a Torn issue, not TornTools. [Bugs & Issues forum thread](https://www.torn.com/forums.php#/p=threads&f=19&t=16204314&b=0&a=0)

**Comment by DeKleineKobini** [comment]
After a quick chat, it is supposedly caused by TT.
