### ISSUE TITLE
Disable flight button

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#394]
**Describe the solution you'd like**
Add an option to disable the flight button if it interferes with the OC finish time.

Should be `false` by default.

**Comment by hvr-lust** [comment]
you need faction AA to get OC time. we can add a feature to scrape events log for OCs we get put into and cache/cookie the ETA for OC to end. consider cancellations...

this could be done as part of this story

**Comment by DeKleineKobini** [comment]
> you need faction AA to get OC time. we can add a feature to scrape events log for OCs we get put into and cache/cookie the ETA for OC to end. consider cancellations...
> 
> this could be done as part of this story

Significant changes like this are better fitted for the new major version.

**Comment by DeKleineKobini** [comment]
In v6, I've added a feature that scrapes the oc page.

Might also add something that reads the events, but using the api instead of page scraping.

**Comment by DeKleineKobini** [comment]
Since there now is an icon, is this still needed?

**Comment by DeKleineKobini** [comment]
Closing as there already are multiple notices already (Torn's notice, Torn's icon and our sidebar timer).
