### ISSUE TITLE
[BUG] Faction deposit log formatting

### ISSUE THREAD

**Issue by factoryman942** [Mephiles/torntools_extension#401]
![image](https://user-images.githubusercontent.com/20996272/108013674-1043f000-7004-11eb-9b73-803eaf1e0928.png)
w/ TT disabled
![image](https://user-images.githubusercontent.com/20996272/108013699-19cd5800-7004-11eb-823e-f71edc2fe098.png)
w/ TT enabled.

The Xan deposit log isn't bolded like the others here, and the BBs have become "undefined"
The unbolding seems to be caused by depositing multiple of an item: 
![image](https://user-images.githubusercontent.com/20996272/108014321-87c64f00-7005-11eb-9078-0f8873a25d3f.png)
Not sure what's made the bloods go undefined though.

**Comment by DeKleineKobini** [comment]
Feature has been removed in v6.
