### ISSUE TITLE
[BUG] ttTravelHome travel_market from DB returned Unknown error

### ISSUE THREAD

**Issue by josephting** [Mephiles/torntools_extension#424]
[UPDATE](https://github.com/Mephiles/torntools_extension/issues/424#issuecomment-792236867): Could be the extension not starting up properly

**Describe the bug**
Travel market not working.

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Go to [Travel Agency](https://www.torn.com/travelagency.php) while you're in torn
2. Helper doesn't load (Refer to screenshots)

```
ttTravelHome.js:198 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'date' in Unknown error
    at ttTravelHome.js:198
```

**Screenshots**

Helper on travel agency doesn't load
![image](https://user-images.githubusercontent.com/1507016/110233193-b6c94400-7f65-11eb-8c8f-ca82dd0a3b50.png)

![image](https://user-images.githubusercontent.com/1507016/110233213-e0826b00-7f65-11eb-8098-30528bf52a09.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by josephting** [comment]
Was trying to update travel_market manually to no avail.
```
fetchRelay('yata__v1', { section: 'travel/export' }).then(result => { console.log('travel market result', result); result.date = new Date().toString(); ttStorage.set({ travel_market: result }, () => { console.log('travel market info set.'); }) });

Promise {<pending>}__proto__: Promise[[PromiseState]]: "pending"[[PromiseResult]]: undefined

background.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

background.html:1 Error handling response: TypeError: Cannot read property 'error' of undefined
    at chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/js/globalFunctions.js:3382:17
```

It seems like turning off the extension and back on again solved it. Could be chrome level issue? 🤔

**Comment by josephting** [comment]
It seems like downtime of yata will cause this to happen and the issue possibly remains until the database is wiped somehow.

More robust checks should be implemented here. Perhaps check if `travel_market` is an object and not a string first?

https://github.com/Mephiles/torntools_extension/blob/c23b16b1597f98891b363ec1a4f4f71f2137a554/torntools/scripts/content/travel/ttTravelHome.js#L198

**Comment by DeKleineKobini** [comment]
Shouldn't be an issue after v6 releases.
