### ISSUE TITLE
Ability to set minimum chance of success for "No Confirm" Revive

### ISSUE THREAD

**Issue by markonthis** [Mephiles/torntools_extension#430]
With the latest changes to the reviving aspect of Torn, it would be extremely helpful to be able to set a minimum success rate required in order for the No Confirm to apply. If the success rate is not within that threshold, then you would still have to manually confirm.

I imagine some folks might wat the ability to set a maximum, but minimum would be the largest majority of the use cases in my opinion.

For example, if I set the minimum threshold to 85% and try to revive someone and only have a 30% chance of success, I would need to confirm the action. But if the chance of success is 98%, I would not need to confirm the revive.

**Comment by markonthis** [comment]
Perhaps also add an option to disable the ability to manually confirm if the success rate is below the minimum threshold.

**Comment by DeKleineKobini** [comment]
This is already planned for v6

**Comment by DeKleineKobini** [comment]
It was already worked on by a contributor, so it will probably be in v5.x

**Comment by Sashank999** [comment]
If there is a possibilty to know how to calcluate the past 24hr revives of a person via the API, then we can do that.
We already have the formula required in Forums at https://www.torn.com/forums.php#/p=threads&f=61&t=16219555&b=0&a=0 .

**Comment by DeKleineKobini** [comment]
We've removed no confirm for revives in general with v6.
