### ISSUE TITLE
[BUG] Total bazaar and display case don't show on own bazaar and display case.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#434]
**Describe the bug**
The total value doesn't show on your own pages.

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Go to [https://www.torn.com/bazaar.php#/](https://www.torn.com/bazaar.php#/) or [https://www.torn.com/displaycase.php#display](https://www.torn.com/displaycase.php#display)
2. No value to be seen.

**Comment by Sashank999** [comment]
It works now. Please close this.
