### ISSUE TITLE
Abroad Countries as a checkbox instead of radio

### ISSUE THREAD

**Issue by Sandbird** [Mephiles/torntools_extension#449]
![download (1)](https://user-images.githubusercontent.com/204934/112740126-11f9bf80-8f83-11eb-855a-18b892d072f4.png)

Could we have these as checkboxes instead of radio buttons ? It would be much easier to select which countries to show bellow than for example clicking Mexico, Cayman and Canada individually to see all closests places and items.

**Comment by DeKleineKobini** [comment]
This is planned to be included in v6.
