### ISSUE TITLE
[BUG] Racing upgrades no longer showing values

### ISSUE THREAD

**Issue by factoryman942** [Mephiles/torntools_extension#490]
Chrome, v5.8;
The numbers and shiny colours are no longer appearing for racing upgrades.
![image](https://user-images.githubusercontent.com/20996272/114720283-cdff0c80-9d2f-11eb-803a-a7de0c785941.png)
![image](https://user-images.githubusercontent.com/20996272/114720366-deaf8280-9d2f-11eb-958e-5748386a2ef9.png)

**Comment by DeKleineKobini** [comment]
This is fixed for 5.9, which should release in a couple of days.
