### ISSUE TITLE
Global chat aliases

### ISSUE THREAD

**Issue by Benguin** [Mephiles/torntools_extension#493]
Add a new page to the settings, 'Chat Aliases', that lets you enter a user ID and a nickname, and then it will show that nickname in chat / on user profiles / user lists instead of the actual username. It helps keep track of people when they've changed their name, without clogging up your friends/enemies lists.

I've been using some CSS to accomplish this: 
```
    a[href="/profiles.php?XID=<id>"]::after{
        content: "Some Dipshit";
        position: absolute;
        left: 0;
        top: -2px;
        width: 100%;
        height: 100%;
        background-color: #efefef;
    }
    a[href="/profiles.php?XID=<id>"] {
        position: relative;
    }
```
But a JS solution with a UI to configure it would be nicer.

For now, just applying it to the chat window would be nice.

If I get time I may create a pull request later, but it's looking to be a busy few weeks ahead.

**Comment by DeKleineKobini** [comment]
Honestly, I do think this works well in chats, but not besides that. For you it might, because you have honors disabled, but I think it's best to only do it for chats in TornTools.
