### ISSUE TITLE
[BUG] Faction armory filter button dissappears on selection, page refresh required to show again

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#50]
**Describe the bug**
Faction armory filter button disappears on selection, page refresh required to show again.

**Expected behavior**
The button shouldn't disappear and the filter should apply upon selection.

**Smartphone (please complete the following information):**
 - Firefox for Android

**Additional context**
Equal to bug 67 on Discord.

**Comment by Mephiles** [comment]
Solved for 4.9
