### ISSUE TITLE
Show your own vault share rather than whole vault value (optional).

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#51]
**Is your feature request related to a problem? Please describe.**
Yes, the vault balance also shows the balance of my spouse.

**Describe the solution you'd like**
Only show my own balance.

**Describe alternatives you've considered**
Deal with it.

**Additional context**
Equal to bug 68 on Discord, although I'd think it's more an suggestion than a bug.

**Comment by Mephiles** [comment]
Solved for 4.10
