### ISSUE TITLE
Countries listed for plushies in invetory

### ISSUE THREAD

**Issue by KenV1040** [Mephiles/torntools_extension#524]
Upon opening your inventory and going to the plushy tab, each plushy you own would have a flag of what country it belongs to. And at the bottom there should be a list of countries that you haven't got plushies from yet. This could be applicable to flowers as well.

**Comment by DeKleineKobini** [comment]
I feel like we are already showing a ridiculous amount of extra information on the items page. I don't think we should add more information.

@Mephiles Thoughts?

**Comment by Mephiles** [comment]
1. yes we can display country flags
2. we already show the ghost rows of what plushies you're missing, so you can see which countries you need to visit, no need to list the countries separately

**Comment by KenV1040** [comment]
I see, my bad. I guess I made this suggestion when I already had all the plushies so I didn't see the ghost rows.
