### ISSUE TITLE
Profile compare rewrite

### ISSUE THREAD

**Issue by hvr-lust** [Mephiles/torntools_extension#526]
**Describe the solution you'd like**
A description of the feature. If possible, provide screenshots of scetches/page edits.

The profile "user info" is pretty cluttered and bloated. There is a lot of unnecessary spacing. We could reduce this spacing but if we want to keep the customisability we will need to rewrite the engine.

It'd be good to be able to start off with a blank canvas then slowly add a "screen", e.g. a comparator like spy, etc. We'll allow the adding of rows and columns. For things like previous fight details, columns may not be appropriate, or add additional work to make it compliant with UX standards, therefore we should only show certain options if appropriate. Maybe restrict to max of 3 columns.

While rewriting, we should allow a locking mechanism. It sucks draging when scrolling a page etc.

Estimation of effort: 
high

**Comment by DeKleineKobini** [comment]
We are working on v6, which is basically a rewrite. Profiles are indeed something that are on the list for significant changes.

**Comment by hvr-lust** [comment]
> We are working on v6, which is basically a rewrite. Profiles are indeed something that are on the list for significant changes.

How do we contribute to v6?

**Comment by DeKleineKobini** [comment]
> > We are working on v6, which is basically a rewrite. Profiles are indeed something that are on the list for significant changes.
> 
> How do we contribute to v6?

[https://github.com/Mephiles/torntools_2](https://github.com/Mephiles/torntools_2)
It's a entirely different system, and we are still working on the details (in the contributor chat on Discord, which I've given you access to).
The issues on that repo aren't yet correct though.

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6.
