### ISSUE TITLE
[BUG] Memory Problems

### ISSUE THREAD

**Issue by Sitethief** [Mephiles/torntools_extension#533]
**Describe the bug**
Over time Torn Tools uses enormous amounts of memory that if not stopped will freeze my system and/or auto close Firefox

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Enable Torn Tools in the Firefox add on window
2. Normal usage of the system, playing of torn, browsing, work, gaming, etc etc
3. Sometimes it takes a few hours, in the case of the screenshots I turned Torn Tools back on around 10 in the evening, and I noticed sudden memory issues around 3 in the afternoon the next day. Note, the system and browser have been running all this time. Not sleep mode engaged in between. The time till this problem seems a bit random, it can be a fast as 30 minutes and as slow as aprox 2 days.

I suspect something in Torn Tools is leaking memory, or having an infinite loop or something that looks like this.

**Screenshots**
[Just enabled Torn Tools](https://ibb.co/J2yzND3) 
[Detected the problem](https://ibb.co/t24LRrJ)
[Managed to disable Torn Tools before my laptop froze or Firefox was autoclosed](https://ibb.co/BKkhZwd)
In this timeframe I was using Torn in a daily manner, no chains/wars or things that required much activity, just some training and crimes done. No trading, no flying, no missions. Just a regular day. And most of it I wasn't even using the laptop.
At the time of the memory spiking I wasn't even playing Torn, I just had it open in one tab while I was doing other things.

**Laptop (please complete the following information):**
 - Machine: DELL XPS-15-7590, i7 9th generation with 16GB memory.
 - OS: Ubuntu 20.04.2 LTS but also 18.04 LTS
 - Browser: Firefox 89.0.1 (64 bit) but also previous versions
 - Torn Tools: version 5.10, but also previous versions

**Comment by Mephiles** [comment]
Thanks for the detailed report. We have had similar reports and the most common line is a Linux-based operating system.

DKK used TornTools for a long time on Firefox (on Windows), and then on another Firefox-based browser and I don't think he had such a problem.

**Comment by Sitethief** [comment]
> Thanks for the detailed report. We have had similar reports and the most common line is a Linux-based operating system.
> 
> DKK used TornTools for a long time on Firefox (on Windows), and then on another Firefox-based browser and I don't think he had such a problem.
> 
> Maybe it's a common issue with a certain browser API that we use? I'm not sure how to debug this issue to be honest.

Feel free to contact me for a debugging session or something. I'm a developer myself, though not really of addons. I know how frustrating this can be.

**Comment by Mephiles** [comment]
From the 15-minute Googling, I just did, seems like memory leaks seem to be a continuous issue for Firefox on Linux-based systems. Seems like there's rather an issue on the browser core level and we can't really do anything about it.

Any suggestions are welcome.

**Comment by DeKleineKobini** [comment]
Since this is a browser issue, rather than on our end, I'll close this one. Should it turn out to actually be TT, please let us know and we'll try to figure it out then.
