### ISSUE TITLE
[BUG] Stealth and Respect not calculating in Targets Tab

### ISSUE THREAD

**Issue by Nikralx** [Mephiles/torntools_extension#541]
**Describe the bug**
Respect and Stealth not calculating on the Target list

**To Reproduce**
Steps to reproduce if it isn't self-explanatory:
1. Click Targets
2. No Numbers under Stealth, Respect despite attacking them

If you feel like the following information is important then please fill in:
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 91

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6. Report again if it's an issue after it' s release.
