### ISSUE TITLE
Pros and cons disappear in Items/Drugs on second view respectively

### ISSUE THREAD

**Issue by sucyhu** [Mephiles/torntools_extension#543]
Describe the bug
Pros and cons disappear in Items/Drugs on second view

To Reproduce
If you click any items at Items/Drugs, TornTools shows its pros and cons.
If you do the same again on the same item (either coming back from another item), pros and cons will not be shown.
If you click on an item you havent in the same session, it shows.

If you feel like the following information is important then please fill in:
Desktop (please complete the following information):

OS: Win10
Browser Chrome
Version 91

**Comment by DeKleineKobini** [comment]
A lot of features in v5, like the drug details, work pretty bad on v5 (the current version). This issue will be resolved with the rewrite / v6. v6 will still take a while to release though.
