### ISSUE TITLE
[BUG] Bad formatting in stocks notifications, when not owned

### ISSUE THREAD

**Issue by carloborreo** [Mephiles/torntools_extension#544]
Click on TT icon on the right of the browser's address bar.
Select the "Stocks" tab.
With the "Search", search any stock you DON'T own.
Click on "Price Info".
The display will be incorrect, making the alerts very hard to use.
If you own the stocks, the formatting will be ok; if you don't, the issue appears.

Screenshot:
![image](https://user-images.githubusercontent.com/68809731/127287905-23d4d7dd-03df-44c0-84d5-3afc17d84783.png)

Issue verified both on Chrome and Firefox.
Workaround: use TAB and SHIFT-TAB keys to move between the alerts.

**Comment by DeKleineKobini** [comment]
Will be closing in favor of v6.
