### ISSUE TITLE
Destination form on travel agency page

### ISSUE THREAD

**Issue by JJins** [Mephiles/torntools_extension#545]
**Describe the solution you'd like**
A description of the feature. If possible, provide screenshots of scetches/page edits.

Hi guys, is it possible to restore the display of the originally existing destination form in the future? Like adding an option in the preferences whether to show that table or not.

**Comment by DeKleineKobini** [comment]
I don't understand what you mean? 

Do you want an option to disable the travel table?

**Comment by DeKleineKobini** [comment]
Closing due to lack of comment.
