### ISSUE TITLE
Stacked Energy Warning Changes

### ISSUE THREAD

**Issue by Jordach** [Mephiles/torntools_extension#547]
Instead of having to click the OK button and then the Torn header at the top left - a button to safely leave the page from the warning screen - without a clickthrough into the gym would be nice.

Currently:
![image](https://user-images.githubusercontent.com/1439852/134693180-1e0006f7-1697-420c-82e9-8d5f349da43c.png)

What it could look like:
![image](https://user-images.githubusercontent.com/1439852/134693446-ad78bc38-9632-4bc5-aeee-8f3b3b38b3ba.png)

**Comment by DeKleineKobini** [comment]
This feature has been removed with v6.
