### ISSUE TITLE
Show the quick items container is not showing.

### ISSUE THREAD

**Issue by abatadev** [Mephiles/torntools_extension#549]
TornTools version:  Version: 6.0.0
Brower Version: 94.0.4606.61 (Chrome)

![image](https://user-images.githubusercontent.com/50708229/135100571-80f26ca2-e978-4e33-9346-f9e9a69c8f77.png)
![image](https://user-images.githubusercontent.com/50708229/135100648-0dd7a127-3899-400c-ae1c-22b9f276a34f.png)

The hotbar no longer appears on top as it used to be on previous versions.

Steps that I tried on fixing the issue.
1. Reinstalling TornTools and giving permissions.
2. Restarting browser.
3. Clearing browser cache.
4. Relogging in Torn.
5. Using TornTools as the only active extension.

Steps that I have not tried to reproduce the issue.
1. Trying on different Chromium-based browsers.

**Comment by DeKleineKobini** [comment]
It's known, but we have no idea why it's that way. We can't replicate it either.

**Comment by Mr-Me-torn** [comment]
I had the same issue when I had more than 25k items in my inventory.
Moved my plushies to my Display Cabinet and the features in the items page worked again.

**Comment by abatadev** [comment]
> I had the same issue when I had more than 25k items in my inventory. Moved my plushies to my Display Cabinet and the features in the items page worked again.

I can confirm the 10k warning dialogue of Torn happens to be the issue as well. I moved my items to my display page and the Quick Items appeared just fine.

**Comment by DeKleineKobini** [comment]
> I had the same issue when I had more than 25k items in my inventory. Moved my plushies to my Display Cabinet and the features in the items page worked again.

Great! We couldn't figure out the cause, but that's it.

**Comment by DeKleineKobini** [comment]
Fixed for 6.0.1
