### ISSUE TITLE
Warning when leaving Torn with no drug cooldown

### ISSUE THREAD

**Issue by carloborreo** [Mephiles/torntools_extension#553]
Many players like to take 3 Xan/day,
It may happen to forget to take it and start traveling, missing an opportunity.
An optional warning when leaving Torn, with no drug CD in place, could prevent the problem.

**Comment by DeKleineKobini** [comment]
This feature already exists, including a lot of other warnings: energy, nerve, **drug cooldown**, medical, education and bank, I might forgotten one as well.
