### ISSUE TITLE
Blurry font in chat box titles when TT enabled

### ISSUE THREAD

**Issue by f2404** [Mephiles/torntools_extension#558]
Browser: Firefox 92.0.1, OS: Windows 10 Pro 21H1

This may sound weird, but with TT enabled, font in chat box titles becomes kinda blurred on the Home page.
With TT disabled or on pages other than Home, the font is fine.

Home page, with TT enabled:
![image](https://user-images.githubusercontent.com/14939413/135624786-178b0065-b182-47fa-b9f9-21bcd7a20ea6.png)

Other pages (e.g., Forums), or TT disabled:
![image](https://user-images.githubusercontent.com/14939413/135624937-90667bc6-eac6-43f7-9fa6-6cab0ab902f8.png)

**Comment by DeKleineKobini** [comment]
Already fixed for 6.0.1.
