### ISSUE TITLE
No import option before entering APIkey

### ISSUE THREAD

**Issue by tn5421** [Mephiles/torntools_extension#565]
There is no ability to import a backup without first entering your API key, which I think is a bit backwards, since an export most assuredly should also contain information about your API key.

I hop between browsers a lot and I think there should be an option to import my settings without being forced to enter my API key first.

**Comment by Sashank999** [comment]
You're a Florida Man ?

**Comment by DeKleineKobini** [comment]
> Separating the exports would be a good idea and I kinda agree with this. But keeping API Key on a remote server isn't a good idea.

What I meant with separating is different content in the exports. Imo, there shouldn't be a difference between these different types of export on their content.

**Comment by Sashank999** [comment]
I know what you meant. Well no, but actually yes. There can be a difference. The export for a different PC or a reinstall on the current PC **can** have the API Key. But for exporting to a remote server which isn't in your control, shouldn't have the API Key.

I see nothing wrong in separating them.

**Comment by tn5421** [comment]
I vastly prefer to have the local export method available, where I am responsible for my own backup file(s) and where I can import whenever I need to. I don't think having the API key exported to a local file is a huge security concern, no more than typical internet access.
