### ISSUE TITLE
[BUG] YATA database update not going through

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#57]
**Describe the bug**
YATA import not working when abroad. 

**Screenshots**
https://imgur.com/wwZkwoe

**Desktop (please complete the following information):**

**Comment by DeKleineKobini** [comment]
Not able to reproduce.

**Comment by Mephiles** [comment]
Should not be an issue anymore as all permissions are granted, etc. If this comes up again, will reopen.
