### ISSUE TITLE
[BUG] Show more is UX unfriendly.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#59]
**Describe the bug**
The show more button on mobile is very UX unfriendly.

**Screenshots**
![Screenshot_20200724-235607](https://user-images.githubusercontent.com/7302579/88438577-5a1b7d80-ce09-11ea-8502-29cc1fc60830.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 10
 - Yandex Browser

**Comment by Mephiles** [comment]
Changed design for 5.0
