### ISSUE TITLE
[BUG] travel agency page broken on FF for android

### ISSUE THREAD

**Issue by Allo101** [Mephiles/torntools_extension#60]
**Describe the bug**
Abroad item info on travel agency page does not load correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/67561579/88458644-6a723d80-ce87-11ea-9001-e8733a2787ec.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Adroid 9
 - Browser Firefox for Android
 - Version 4.8

**Comment by DeKleineKobini** [comment]
I've added a small safety for 4.9.
It isn't a solution, but rather a possible bypass. It's incredibly hard to fix something that is only an issue on Firefox for Android (or Kiwi Browser) due to the lack of debugging/development features.

**Comment by DeKleineKobini** [comment]
As Firefox Mobile no longer supports our extension, I'll close this issue.
