### ISSUE TITLE
Vault balance

### ISSUE THREAD

**Issue by carloborreo** [Mephiles/torntools_extension#605]
![image](https://user-images.githubusercontent.com/68809731/142704096-df1fbced-6724-41bf-abd0-28ac2a71c9a6.png)

![image](https://user-images.githubusercontent.com/68809731/142704198-ea14ee72-9ce5-48c4-badc-0488d5959ced.png)

The vault balance is incorrect.
My spouse is permanently fedded, so is not acting on the vault.
I access Torn from different devices, all with TT (tablet and phone with Kiwi, two computers with Chrome).
The API call https://api.torn.com/user/?selections=money&key= returns the correct value

**Comment by DeKleineKobini** [comment]
Vault balance is a though one, as it's not just an api endpoint. 
The api only gives the amount of cash in your vault, if you are the owner of the property. It doesn't know which part of it is yours and which part of it is your spouses.

**Comment by carloborreo** [comment]
I agree that, in general, tracking the amount owned by two spouses is very difficult, imo even unrealistic, unless some specific conditions are met (for instance, I only play on one device).
But since I selected the option "Show the total balance instead of yours", this should not be a problem: TT should just get the total vault value from the user/money API call and display it.

**Comment by DeKleineKobini** [comment]
Tbh, I'm more inclined to completely scrap the feature. I'll ask @Mephiles' opinion.

**Comment by Mephiles** [comment]
I understand the reasoning to scrap the feature. But I feel like most users who use it wouldn't understand and it'd upset people that we'd rather remove than fix it :D .

Is there any way we could simplify but still keep it? If not then sure, we can scrap it. As it seems to cause more trouble than good for most users.

**Comment by carloborreo** [comment]
Since tracking the amounts in shared vaults is unrealistic, TT could simply display the total content from the user/money API call.

**Comment by DeKleineKobini** [comment]
@Mephiles 
> I understand the reasoning to scrap the feature. But I feel like most users who use it wouldn't understand and it'd upset people that we'd rather remove than fix it :D .

It's been broken for months, without it being worked on. Someone would have to pick it up, but the majority of the active devs (including me), can't.

> Is there any way we could simplify but still keep it? If not then sure, we can scrap it. As it seems to cause more trouble than good for most users.

A vault tracking system that does not rely on the activity log will always be flawed, it will never be perfect. I think the current system, if it would be working, would the least worst alternative.

@carloborreo 
> Since tracking the amounts in shared vaults is unrealistic

Vault tracking itself isn't unrealistic, as the activity log gives a great way to do it. But TT doesn't use the log api. I'm of the believe that the log api shouldn't be used in userscripts or extensions, unless it's a one-time thing, instead it should be used on actually hosted platforms.

> TT could simply display the total content from the user/money API call.

As this only displays the total value in the property of the owner, I don't like that.
1. If you share your vault, it's useless, unless you decide that the money is actually shared and not split.
2. If you live in your spouses property, it's useless.
3. If you live in a rented property, it's useless.

**Comment by DeKleineKobini** [comment]
This feature has now been removed.
