### ISSUE TITLE
[BUG] when using search function in faction filter, additional info stays

### ISSUE THREAD

**Issue by Allo101** [Mephiles/torntools_extension#61]
**Describe the bug**
When using the new serch function in the faction members list, all torntools additional info for non visible members stays visible

**Expected behavior**
Ony additional info of searched member should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/67561579/88458972-9262a080-ce89-11ea-847c-132bc1e67964.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - Version Beta 4.9

**Comment by Mephiles** [comment]
Solved for 4.9
