### ISSUE TITLE
Add stakeouts on sidebar

### ISSUE THREAD

**Issue by vALT0r** [Mephiles/torntools_extension#650]
Add a list of custom selected player IDs to show a timer with hosp time or travel status (maeby aprox landing time?). It would be a complement to Stakeout and Bounties.

**Comment by DeKleineKobini** [comment]
I don't see much added value besides the already existing stakeouts.

**Comment by vALT0r** [comment]
I see it as an enhanced stakeout, maeby a rework?

**Comment by daanjo3** [comment]
Yeah I think @vALT0r has a good idea, the current stakeout implementation could be extended on to serve as a full (somewhat accurate) target list.

**Comment by DeKleineKobini** [comment]
> I see it as an enhanced stakeout, maeby a rework?

I fail to see how stakeouts require a rework. The list is 1 click away?

> Yeah I think vALT0r has a good idea, the current stakeout implementation could be extended on to serve as a full (somewhat accurate) target list.

Stakeouts are not meant as target list and having it as part of the sidebar will, wrongly, have people believe that it is. You should never have more than a handful of players on your stakeouts, whereas a target/chain list should probably be more around 100 players.
