### ISSUE TITLE
Mission task for "Get Thinks Jumping" inaccurate

### ISSUE THREAD

**Issue by DieGoldeneEnte** [Mephiles/torntools_extension#678]
The Task description of torntools is 
 > Deal 2,000 - 50,000 and receive 1,000 - 25,000 damage based your max life.

but for me (lvl11 with 425 max live) it is only cause 400 damage receive 200 damage.

Maybe it doesn't really make sense to give numbers, if it the possible range is so large.

**Comment by DieGoldeneEnte** [comment]
Same for "Batshit Crazy"
 > Inflict 212 - 1,700 (based on your maximum life) damage with Penelope

I am still lvl 11 with 425 max health, but only need to do 106 damage.

**Comment by DeKleineKobini** [comment]
Fixed it for the next version.
