### ISSUE TITLE
sortable profile user info (up/down arrows)

### ISSUE THREAD

**Issue by Allo101** [Mephiles/torntools_extension#68]
To change the order of the selected stats to show in the profile user stats, you need to remove and re-add them to get the order you want.

Add up/down arrows when editing to move a single stat up or down in the selection.
![image](https://user-images.githubusercontent.com/67561579/88460473-584acc00-ce94-11ea-93d6-30a17bceb3b0.png)

**Comment by Mephiles** [comment]
Added for 4.10
