### ISSUE TITLE
Click on the Life Bar -> Redirect to a link / Or use a specific medical item

### ISSUE THREAD

**Issue by vhoanghac** [Mephiles/torntools_extension#680]
Recommendation:

For example, when I click on the Life Bar it will send me to my Faction's medical page at https://www.torn.com/factions.php?step=your#/tab=armoury&start=0&sub=medical

Or we can allow it to use a specific item in my inventory, such as blood bags?

**Comment by DeKleineKobini** [comment]
Life is a bar that I have no interest to added a link to. There is no single link that works in my opinion, but adding a configurable link is not great either.
