### ISSUE TITLE
"Align Torn to the left" broken

### ISSUE THREAD

**Issue by AeSix** [Mephiles/torntools_extension#700]
Torn is no longer aligned to the left of the viewport.
When the option is enabled or disabled, there is no change in visual appearance. 
This issue occurred after Torn was seemingly updated with some new layout code (css possibly?) about 2 or 3 days ago.  The entire layout of the site was broken for all players.  After a few minutes, it was advised we ctrl-f5 to clear the cache.  Doing so resolved the layout issues the torn devs had caused.  At the time, the left alignment was still properly being utilized, however after restarting my computer (and thus Chrome and Torn Tools), the left alignment is broken. 

Normally I wouldn't make an issue ticket for something some mild, however I'm not sure how many people use this feature and if it would get noticed at all.  I'm unable to test any other configurations, but am willing to provide additional information if needed.

Operating System:
Windows 11 Pro
10.0.22622 Build 22622

Browser:
Chrome is up to date
Version 106.0.5249.119 (Official Build) (64-bit)

Torn Tools:
Official from Chrome app store
Version 6.9 / Sept 16 2022

**Comment by DeKleineKobini** [comment]
We fixed it yesterday, and I'm hoping to release today.

**Comment by AeSix** [comment]
Confirming issue is resolved.  Thank you all!
