### ISSUE TITLE
personal stat bars overlaid in Torn Tools config pages (minor annoyance)

### ISSUE THREAD

**Issue by AeSix** [Mephiles/torntools_extension#701]
the energy/nerve/happy/health bars are overlaid on every page of the Torn Tools config page. 
When looking to copy the css for the section (in debug screen on Chrome) - I widened the debug view, and the 4 bars went from a vertical orientation to a horizontal orientation, and added in the entire toolbar from the game (including buttons for home/city/missions/etc) 

If it's not possible to remove this, would it be possible to change the z-order so it is displayed behind the config screen data?

The offending code (couldn't figure out how to copy it as text, sorry)
![1wK8wco 1](https://user-images.githubusercontent.com/5191757/195840332-d966aa0c-7a96-43e5-9157-a622066a1a74.png)

The offending visuals
![4uiLllq 1](https://user-images.githubusercontent.com/5191757/195840369-8be086f2-c5c5-41b0-9b2b-c4433b231ea6.png)

Windows 11 Pro / 10. 0.22622 Build 22622
Chrome Version 106.0.5249.119 (Official Build) (64-bit)
Torn Tools 6.9

**Comment by DeKleineKobini** [comment]
Thanks for the report, will look into it for the next version or the one after that depending in how fast I find it, as I want to release today.

**Comment by AeSix** [comment]
Awesome!  Thank you!

**Comment by DeKleineKobini** [comment]
Apparently another contributor fixed it already, as I had to downgrade to be able to replicate.

**Comment by DeKleineKobini** [comment]
Ah, it uses left align to make place. So because I fixed left align, it followed.

**Comment by AeSix** [comment]
Just wanted to confirm, I got 6.9.1 - and left is aligned properly, as expected.  Thank you all! :)
