### ISSUE TITLE
Addiction in sidebar

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#711]
Show company addiction modifier in sidebar (companies/employees api call).

**Comment by c0nradLC** [comment]
I'd like to try this if no one is already doing it.

**Comment by c0nradLC** [comment]
I'd like to try this if no one is already doing it.

**Comment by Sashank999** [comment]
No one is doing it currently, it would be assigned if someone is working on it.
If you want to deal with a suggestion or a bug, look at its status in its associated project.
This is currently in `Triage` section of `Suggestions` project. The maintainer should first move it to `To Do` section in order for anyone to be working on it. He might not have yet planned the feature completely.

You can ask the maintainer either in-game or in TornTools Discord server(preferred).

**Comment by Sashank999** [comment]
> I'd like to try this if no one is already doing it.

No one is doing it currently, it would be assigned if someone is working on it.
If you want to deal with a suggestion or a bug, look at its status in its associated project.
This is currently in `Triage` section of `Suggestions` project. The maintainer should first move it to `To Do` section in order for anyone to be working on it. He might not have yet planned the feature completely.

You can ask the maintainer either in-game or in TornTools Discord server(preferred).

**Comment by DeKleineKobini** [comment]
**Proposal**

- Disabled on mobile and tablet (because they have no sidebar).
- Only when the user is in a company (a system job does not count).
- Set the update time to be in the first update cycle after like 18:30 TCT (by then it should have updated).
- Display as "Company Addiction".

**Comment by DeKleineKobini** [comment]
> I'd like to try this if no one is already doing it.

Feel free to either work on it, or propose changes to my proposal.

**Comment by c0nradLC** [comment]
Cool, I'm working on it on my free time, a suggestion I have would be to make the "Company Addiction" label redirect to the company employees page, just like the OC timer redirects to the faction crimes page.

**Comment by DeKleineKobini** [comment]
> a suggestion I have would be to make the "Company Addiction" label redirect to the company employees page, just like the OC timer redirects to the faction crimes page.

Sounds perfect, thanks.

**Comment by DeKleineKobini** [comment]
Live for end users already.
