### ISSUE TITLE
Incorrect cooldown time when cd is beyond 24h

### ISSUE THREAD

**Issue by RicoloveFeng** [Mephiles/torntools_extension#719]
![image](https://user-images.githubusercontent.com/44725122/211951989-0826468f-5125-4597-b96f-cacaa3eb14ba.png)

![image](https://user-images.githubusercontent.com/44725122/211952015-1cbca296-1ecd-4458-8a73-89c6fbbb350f.png)

Is it a bug?

**Comment by DeKleineKobini** [comment]
I thought I fixed that a long time ago, but I'll look into it.
