### ISSUE TITLE
Request: Calendar start-day option

### ISSUE THREAD

**Issue by AeSix** [Mephiles/torntools_extension#725]
First, I understand that a) a good portion of the world uses calendars which start on Mondays; and b) that the calendar isn't heavily utilized.  However, as for 40+ years, I have looked at calendars which start on Sunday, the in-game cal is rather difficult for me. 

So, if anyone who actually can add an option to shift the calendar to start on Sundays, and is bored enough to implement it - I'd love it. 
I am no where near at the ability to be able to contribute code to this.  I can help test if needed.  

(I've searched the issues, didn't find anything requesting this.  If I've missed it, I apologize)

**Comment by DeKleineKobini** [comment]
I do agree that a Sunday based calendar as default is ridiculous, this is not the kind of feature that I want to add to TornTools and I'd rather have Torn change it. They are adding the weekdays to it though, so that should help at least.
