### ISSUE TITLE
Wrong value of Items in Home vs Items

### ISSUE THREAD

**Issue by CJthisis** [Mephiles/torntools_extension#729]
In the Home tab, the value of my items is over 3 million $ higher than in the Items tab:
(If this is caused by me, please tell me how to fix this)

The pictures were taken 1 minute apart, and this issue has been the same for a few days, even on different computers. 

![net worth in Home](https://user-images.githubusercontent.com/99442347/220377770-b088c4f9-6c24-45c0-a6f3-c880fb415c3a.png)

![value of items](https://user-images.githubusercontent.com/99442347/220377809-4f76c2d0-fd86-4f72-93be-b58ef5bced55.png)

**Comment by DeKleineKobini** [comment]
Live Networth uses the networth value.
Item value uses the total sum of market values.

They are calculated differently (by Torn itself), so they often won't be the same.
