### ISSUE TITLE
[BUG] Faction announcment "Show Full Page" breaks when chain log is displayed

### ISSUE THREAD

**Issue by Allo101** [Mephiles/torntools_extension#74]
**Describe the bug**
The Faction announcment "Show Full Page" fails to load correctly when the chain log is open

--not a massive issue, just something i noticed

**To Reproduce**
1. Open the latest hits log on the My faction page
2. Reload page
3. "Show Full Page" checkbox dissapears completely and scroll bar returns

**Desktop:**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - Version Beta 4.9

**Comment by Mephiles** [comment]
Solved for 4.9
