### ISSUE TITLE
New button style ignorance

### ISSUE THREAD

**Issue by sucyhu** [Mephiles/torntools_extension#743]
Hello, this is a suggestion to choose to ignore the new Torn button style, or at least the font-family for class torn-btn  , because currently the buttons are hard to read. We would appreciate if this could be solved.
Thanks in advance.

**Comment by Kwack-Kwack** [comment]
Whilst there has been lots of talk about this, I'm personally not sure it would fit the scope of the extension. Previously torntools has been quite against manually reverting changes that the torn devs push out, and I doubt this would be any different.

There are userscripts offering this functionality (see [here](https://github.com/br41nslug/torn-brainscripts/blob/main/scripts/revert-button-style.user.js)) that can be installed via tampermonkey.
