### ISSUE TITLE
Show more cooldown end time

### ISSUE THREAD

**Issue by RicoloveFeng** [Mephiles/torntools_extension#747]
So far there are only 5 cooldown have their end time shown in sidebar.

```js
if (
  ["Education", "Racing", "Drug Cooldown", "Booster Cooldown", "Medical Cooldown"].includes(
	  tooltip.getElementsByTagName("b")[0]?.textContent
  )
) {
```

 Can we have more support for timers?

* Bank Investment
* Organized Crime
* Reading Book

**Comment by Sashank999** [comment]
Added in 27ba616e51562db63e6ea75a982d1061b79b3adf .
