### ISSUE TITLE
Suggestion Show job points on mouse hover over the job in the side bar

### ISSUE THREAD

**Issue by ItDidntCatchFire** [Mephiles/torntools_extension#748]
Show the job points that you currently have when you mouse over the job in your sidebar, I mainly open my job to check how many points that I have at the moment and this would save me from having to do that.

**Comment by ItDidntCatchFire** [comment]
I don't mind working on this if it's deemed not important enough for @c0nradLC to work on however I don't plan on continuing to work on this project as I don't have the time to commit to that. :)

**Comment by Kwack-Kwack** [comment]
For clarity, did you mean a tooltip on the "job" icon at the top of the sidebar or the actual job page in the links?

**Comment by ItDidntCatchFire** [comment]
<img width="298" alt="image" src="https://github.com/Mephiles/torntools_extension/assets/28661573/0061991c-a9ff-470a-9214-5e4bdcb08875">

This one here

Receptionist of Kite Store (Fitness Center - 56 points)

Prehaps change the text to be something like this though I'm not attached to how it looks just want the functionality.
