### ISSUE TITLE
Bar Links no longer linking

### ISSUE THREAD

**Issue by iarp** [Mephiles/torntools_extension#758]
Firefox 115.0.1
TT 6.14.0

My Energy and Nerve bar links are no longer linking. I tried disabling and saving and then enabling and saving the associated checkbox without any luck.

Looking at [the bar links code](https://github.com/Mephiles/torntools_extension/blob/master/extension/scripts/features/bar-links/ttBarLinks.js), if I try to replicate the `document.find("[class*='bar__'] [class*='energy__']")` within firefoxs' console I get:

```js
document.find("[class*='bar__'] [class*='energy__']")
Uncaught TypeError: document.find is not a function
    <anonymous> debugger eval code:1
```

but I'm not 100% certain if document is correct in the scope of console or not. JS isn't really my thing.

**Comment by Sashank999** [comment]
Torn devs changed sidebar layout yesterday leading to the break down of the following features:
- Bar Links
- Cooldown End Times
- Taking energy giving items via Quick Items
- Hide Level Up Option
- Highlight Energy and Nerve Refills
- Medical Life on medical items

All the fixes for the features have been pushed to the `master` branch. After being tested by our beta testers, those fixes will be packed and released to the extension stores.
