### ISSUE TITLE
[BUG] Mobile gym page not working correctly.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#76]
**Describe the bug**
The gym tab on mobile isn't rounded and doesn't show the TornStats graph.

**Expected behavior**
Corners should be rounded and the graph should be shown.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/7302579/88487382-d4244180-cf84-11ea-8f44-af1ea6ed767c.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 10
 - Yandex Browser
 - Beta 4.9

**Comment by DeKleineKobini** [comment]
Rounding has been solved for 4.9.

**Comment by Mephiles** [comment]
Made Gym Graph available for Mobile for 4.9
