### ISSUE TITLE
"fill max" on bits n'  bobs returns " You cannot buy that item in this country." while in Torn.

### ISSUE THREAD

**Issue by iarp** [Mephiles/torntools_extension#771]
Title kinda says it all. I'm unsure when this started happening but now everytime i use fill max i get " You cannot buy that item in this country. ". I have to hand type in 100 to buy anything.

**Comment by Kwack-Kwack** [comment]
Are you up-to-date? Issue should have been fixed in 04cb283f6de7b15993b114ea382025460783adc8

**Comment by iarp** [comment]
The release from 16 minutes ago? No not yet. The time between thinking of opening this issue and then opening it I hadn't see that.

**Comment by Kwack-Kwack** [comment]
Fair enough, I assumed you would load it unpacked from the github (most people that open issues here rather than in-game do, and often forget to update their local copy). 
6.17 is live on FireFox, and will be live on Chrome soon (it normally takes a little extra to be live there).

**Comment by iarp** [comment]
Force updated firefox extension and all is well. Thanks! I use github a bunch so it hadn't crossed my mind to open something in game itself.
