### ISSUE TITLE
Incorrect description of the misson"A Problem at the Tracks"

### ISSUE THREAD

**Issue by cosing** [Mephiles/torntools_extension#778]
![image](https://github.com/Mephiles/torntools_extension/assets/63569926/e1a16a51-c5c3-40e9-a8bf-ade1019e877e)

When I was given this quest, I threw out my heg randomly without reading the original description carefully. that was my mistake.

My native language is not English. I'm not sure if my understanding of 'gnus' is off, or what has come up with this quest in the game version change. Maybe this description needs to be updated.

https://github.com/Mephiles/torntools_extension/blob/855fd9ff0fa06a56610aa23b9da6ad3a54156486/extension/scripts/features/mission-hints/ttMissionHints.js#L38-L41

Thank you guys for the plugin.

**Comment by Kwack-Kwack** [comment]
Your understanding is correct. I don't believe these hints were written by the TT team (pinched from a spreadsheet I believe) but the hint does seem to suggest that grenades would be fine.
