### ISSUE TITLE
"A Thor Loser" task inaccuracy

### ISSUE THREAD

**Issue by Bobogoobo** [Mephiles/torntools_extension#803]
The task text for the "A Thor Loser" mission states "hit 8-16 unique body parts." However, there are only 14 body parts, according to [the wiki](https://wiki.torn.com/wiki/Attack#The_Player_Model), though I haven't checked my logs extensively.

(It could also be worth mentioning NPCs as a good way to do it, though players familiar enough to do them probably know already.)

https://github.com/Mephiles/torntools_extension/blob/4f27d876b1a0d27a80d31ca451a616c069f6e8a8/extension/scripts/features/mission-hints/ttMissionHints.js#L42-L45

**Comment by Kwack-Kwack** [comment]
This hint is sourced from Ched himself:

https://www.torn.com/forums.php#/p=threads&f=19&t=16130409&b=0&a=0&start=0&to=19915206

**Comment by Bobogoobo** [comment]
From some searches I did about this mission, it seems like around that time they reduced the number of body parts in the game from 16 to 14. But I don't have a source. I currently have the Expert contract and the requirement is 14 parts. ![image](https://github.com/user-attachments/assets/d3d396e1-7be7-4860-bb5d-4c700f9fb097)
