### ISSUE TITLE
Make the status bars link to their relevant sections in Torn.

### ISSUE THREAD

**Issue by DeKleineKobini** [Mephiles/torntools_extension#81]
**Describe the solution you'd like**
Make the status bars link to their relevant sections in Torn. Ex: Clicking the energy bar takes you to the gym page, clicking the nerve bar takes you to the crimes page.

**Additional context**
Suggestion 50 on Discord.

**Comment by DeKleineKobini** [comment]
I'm planning a popup redesign, which would also solve this.

**Comment by Mephiles** [comment]
Added for 4.10
