### ISSUE TITLE
Can flying energy wasted warning be based on time remaining until full instead of total time to full?

### ISSUE THREAD

**Issue by iarp** [Mephiles/torntools_extension#812]
I fly a lot and one of the things I can do when flying to South Africa is burn my energy to 30/100 and more often than not I will arrive back in Torn within the 15 minute window of the final energy tick to 100. Sometimes I'll go to 20 or 25 depending on how close i am to the next tick.

I noticed that even at 20/100, which takes 4 hours to full, with a "take around 3 hour 38 minutes" message, it still says that "Starting this flight will waste some energy".

Looking at the code on [line 37](https://github.com/Mephiles/torntools_extension/blob/b6a4ba01f453a48e004aec1028aa7ac1fabad4ca/extension/scripts/features/abroad-energy-warning/ttAbroadEnergyWarning.js#L37) I'm unable to figure out where userdata.energy.fulltime is actually set so I'm assuming its based on the full time necessary to go from 0 to 100. Although, as i think about it writing this out, any time over 3 hours and 28 minutes shouldn't be triggering an energy wasting warning message.

Secondary thought as I'm writing this, or maybe the warning isn't being updated as I burn the energy so the logic never hides it... hmm.

![image](https://github.com/user-attachments/assets/674e97e2-fcdb-4c63-9b76-db655928ba66)

**Comment by DeKleineKobini** [comment]
That warning is based on the api data we pull in the background and it uses the time provided by Torn. We only pull this data every 30 seconds (by default, could be configured to be slower), but after an update it should be showing correctly.

**Comment by iarp** [comment]
Gotcha ok, I thought the data was coming from the page itself.
