### ISSUE TITLE
Stat projection

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#92]
**Describe the solution you'd like**
Project future stat growth in Gym table.

**Comment by DeKleineKobini** [comment]
Is this something that is actually needed? I don't see much need for this.

**Comment by Mephiles** [comment]
I don't see much need either but some people relied on this from Doc's times so I added it here for consideration.

**Comment by DeKleineKobini** [comment]
Only reason to add this is "because DrN" had it. Not a valid reason.
