### ISSUE TITLE
Disable the Gym area highlighting

### ISSUE THREAD

**Issue by Mephiles** [Mephiles/torntools_extension#95]
**Describe the solution you'd like**
Disable the Gym area highlighting when all Gym stats training has been turned off.

**Comment by Mephiles** [comment]
Added for 4.10

**Comment by Mephiles** [comment]
Broken on mobile

**Comment by Mephiles** [comment]
This has proven to be more difficult to achieve as expected. Might be considered later on.

**Comment by Sashank999** [comment]
Added this already. Close this please.
